qos_drv: include mod_devicetable.h
Fix missing mod_devicetable.h since some declarations splitted out
platform_device.h

qos-module/files/qos/drv/qos_drv.c:186:34: error: array type has
incomplete element type 'struct of_device_id'

Signed-off-by: Binh Nguyen <binh.nguyen.uw@renesas.com>